language: generic #for issues with travisci thinking the code should be ruby.
sudo: required
services:
  - docker

before_install:
  - docker build -t kwyjibojones/docker-react -f Dockerfile.dev .

script:
  - docker run kwyjibojones/docker-react npm run test -- --coverage