sudo: required
services:
  - docker

before_install:
  - docker build -t KwyjibojonesJr/docker-react -f Dockerfile.dev .

script:
  - docker run KwyjibojonesJr/docker-react npm run test -- --coverage
